/**
 * Ported from GridBeat (Flutter) lib/features/schedule/data/circuit_facts.dart —
 * curated, offline circuit facts for every circuit on the modern F1
 * calendar (26 circuits). Transcribed programmatically (a Python script
 * parsed the Dart source's struct literals directly) rather than by hand,
 * to avoid transcription errors across 19 fields x 26 circuits.
 *
 * This is a *frontend fallback* layered under the Supabase `CircuitDetails`
 * row, exactly like the Dart original: when Supabase has richer data it
 * wins, otherwise this file guarantees every current-calendar circuit
 * shows a real, populated guide instead of "no extended guide yet" — which
 * is what every circuit showed before this existed, since this local dev
 * environment's Supabase credentials are a placeholder that never
 * resolves (see CLAUDE.md).
 *
 * All values are public F1 knowledge, as of the 2025 season per the
 * source file. Lap records are official race records (not qualifying).
 */

export interface CircuitFacts {
  circuitId: string;
  country: string;
  city: string;
  /** km, e.g. "5.412". */
  lengthKm: string;
  /** Race laps, e.g. "58". */
  laps: string;
  turns: string;
  /** Race-observed top speed, km/h. */
  topSpeedKmh: string;
  elevationChangeM: string;
  drsZones: number;
  firstGp: number;
  description: string;
  /** 3 short pill tags, e.g. ["HIGH-SPEED", "FLOWING", "STREET-STYLE"]. */
  character: string[];
  /** [driver, time, year] — official race lap record. */
  lapRecord: [string, string, string];
  /** 2 one-line historical moments. */
  notableMoments: string[];
  /** 1-5, how easy overtaking is. */
  overtakingRating: number;
  bestSector: string;
  /** Usually "Clockwise"/"Anticlockwise" — Suzuka's figure-8 layout is genuinely both. */
  direction: string;
  type: string;
  designer: string;
  mostWins: string;
}

const CIRCUIT_FACTS: Record<string, CircuitFacts> = {
  albert_park: {
    circuitId: "albert_park",
    country: "Australia",
    city: "Melbourne",
    lengthKm: "5.278",
    laps: "58",
    turns: "14",
    topSpeedKmh: "335",
    elevationChangeM: "5",
    drsZones: 4,
    firstGp: 1996,
    description: "A semi-permanent street circuit laid out around the shores of Albert Park Lake, right in the middle of Melbourne. First joining the calendar in 1996 after taking over the Australian GP from Adelaide, it spent two decades with a reputation as a boring processional track before a comprehensive 2022 reprofile changed everything. The old Turn 9–10 chicane was ripped out and replaced with a fast sweeping right, corner speeds were lifted across every sector, and a fourth DRS zone was added down the back straight to make overtaking genuinely possible. What emerged is a driver's favourite - full-throttle time is above 75%, the walls sit close in the tricky middle sector, and mistakes on the aggressive kerbs punish immediately. As the traditional season opener (a role now shared with Bahrain), Albert Park sets the tone for the year: cars are fresh, teams are learning, and the mid-March Melbourne weather can produce anything from stifling heat to storms rolling off Port Phillip Bay.",
    character: ["HIGH-SPEED", "FLOWING", "STREET-STYLE"],
    lapRecord: ["Charles Leclerc", "1:19.813", "2024"] as [string, string, string],
    notableMoments: ["Verstappen crashes out on lap 4 in 2024 while leading", "2002 pole-to-flag from Schumacher in the rain-affected opener"],
    overtakingRating: 3,
    bestSector: "Turns 9–10 sweepers",
    direction: "Clockwise",
    type: "Semi-street",
    designer: "Herrmann Tilke (reprofile)",
    mostWins: "Michael Schumacher (4)",
  },
  bahrain: {
    circuitId: "bahrain",
    country: "Bahrain",
    city: "Sakhir",
    lengthKm: "5.412",
    laps: "57",
    turns: "15",
    topSpeedKmh: "330",
    elevationChangeM: "17",
    drsZones: 3,
    firstGp: 2004,
    description: "Purpose-built in the desert south of Manama and designed from a blank sheet by Hermann Tilke, Bahrain's outer layout is one of the most overtaking-friendly modern venues on the calendar. Three long straights each feed into heavy braking zones - Turn 1 in particular is a 320 km/h stop to 100 km/h that regularly produces first-lap chaos. Held as a night race since 2014, cool track temperatures mask the enormous rear-tyre degradation that erupts once the sun sets and stint lengths shorten. The abrasive desert-sand-dust surface eats compounds, forcing two or even three-stop strategies that transform the race into a rolling chess match. It has hosted the season opener nine times, giving teams their first true read on the pecking order - and the Sakhir circuit has hosted some genuinely defining moments, from Grosjean's 2020 fireball crash to the 2021 Hamilton–Verstappen title-defining opener decided on track limits at Turn 4.",
    character: ["STOP-AND-GO", "HEAVY-BRAKING", "ABRASIVE"],
    lapRecord: ["Pedro de la Rosa", "1:31.447", "2005"] as [string, string, string],
    notableMoments: ["Grosjean's survival crash through the barriers in 2020", "Hamilton vs. Verstappen 2021 opener - decided by track limits"],
    overtakingRating: 4,
    bestSector: "Turns 1–4 braking zone",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Hermann Tilke",
    mostWins: "Lewis Hamilton (5)",
  },
  jeddah: {
    circuitId: "jeddah",
    country: "Saudi Arabia",
    city: "Jeddah",
    lengthKm: "6.174",
    laps: "50",
    turns: "27",
    topSpeedKmh: "360",
    elevationChangeM: "10",
    drsZones: 3,
    firstGp: 2021,
    description: "The fastest street circuit in F1 history - average lap speeds sit above 250 km/h between concrete barriers that rarely give more than a few metres of run-off. Blind, banked left-handers around the seafront corniche require pilots to commit to a corner before they can see the apex, and a series of high-speed right kinks in the final sector are taken flat-out at 300+ km/h. The 27 turns include several near-continuous sequences where the car is loaded from one direction to the other with no relief, generating cornering G-loads normally reserved for permanent circuits. Jeddah joined the calendar in 2021 as part of Saudi Arabia's sport-diversification push, and immediately delivered drama with the Hamilton–Verstappen title fight collision that year. The narrow corridors punish qualifying mistakes brutally - Charles Leclerc's 2023 crash in Q2 ended his weekend before it began - and the safety car probability is among the highest on the calendar, with every race so far requiring at least one neutralisation.",
    character: ["HIGH-SPEED", "STREET-CIRCUIT", "BLIND-CORNERS"],
    lapRecord: ["Lewis Hamilton", "1:30.734", "2021"] as [string, string, string],
    notableMoments: ["Verstappen–Hamilton title fight collision in 2021", "Alonso's 100th podium at 41, then losing it, then getting it back - 2023"],
    overtakingRating: 3,
    bestSector: "Turns 22–27 flat-out kink complex",
    direction: "Clockwise",
    type: "Street",
    designer: "Hermann Tilke",
    mostWins: "Max Verstappen (2)",
  },
  shanghai: {
    circuitId: "shanghai",
    country: "China",
    city: "Shanghai",
    lengthKm: "5.451",
    laps: "56",
    turns: "16",
    topSpeedKmh: "335",
    elevationChangeM: "8",
    drsZones: 2,
    firstGp: 2004,
    description: "Designed in the shape of the Chinese character 上 (\"shàng\", meaning \"above\"), Shanghai International Circuit is one of the most instantly recognisable layouts on the calendar. The signature Turn 1–3 double-apex spiral tightens continuously through 270 degrees, punishing anyone who commits their turn-in too early - get it wrong and you're either wide onto the runoff or completely off-line for the exit. A 1.2-kilometre back straight into the hairpin at Turn 14 is the prime overtaking spot, activated by two DRS zones that make late-braking moves an every-lap possibility. Built on marshland and drained during construction, the circuit sank slightly over time and required a full resurface for its 2024 return after a five-year hiatus. The Chinese GP has produced championship-defining races since its 2004 debut - from Schumacher's inaugural win to Hamilton's beached car in the 2007 title decider - and Verstappen's 2024 sprint-and-race sweep marked the venue's modern rebirth.",
    character: ["TECHNICAL", "LONG-STRAIGHTS", "FLOWING"],
    lapRecord: ["Michael Schumacher", "1:32.238", "2004"] as [string, string, string],
    notableMoments: ["Hamilton beaches his McLaren in the pit entry, 2007 title-decider", "Ricciardo's wet-tyre gamble win in 2018"],
    overtakingRating: 4,
    bestSector: "Turns 1–3 decreasing radius",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Hermann Tilke",
    mostWins: "Lewis Hamilton (6)",
  },
  suzuka: {
    circuitId: "suzuka",
    country: "Japan",
    city: "Suzuka",
    lengthKm: "5.807",
    laps: "53",
    turns: "18",
    topSpeedKmh: "325",
    elevationChangeM: "40",
    drsZones: 2,
    firstGp: 1987,
    description: "The only figure-8 layout on the calendar and universally rated a driver's favourite, Suzuka is the truest test of a Grand Prix car and a Grand Prix driver anywhere in the world. Designed by John Hugenholtz as a Honda test track in 1962, the circuit crosses over itself at the Spoon-to-Casio flyover - a genuinely rare feature - and every corner in Sector 1 (the Esses) demands maximum commitment through a rhythm of alternating direction changes at 250+ km/h. 130R was flat-out even before ground effect returned, taken at 320 km/h with just a light lift for setup - a corner so famous it has its own signage. The Spoon Curve's decreasing radius rewards patience over aggression, and the run to the chicane is one of the calendar's classic overtaking spots. Weather is the perpetual wildcard: October in Japan puts the race squarely in typhoon season, and the 2014 tragedy of Jules Bianchi's crash in monsoon conditions remains one of the sport's most sombre moments. Home crowd support for Honda-powered cars and Japanese drivers gives Suzuka a unique atmosphere no other venue matches.",
    character: ["DRIVERS-FAVOURITE", "FLOWING", "HIGH-COMMITMENT"],
    lapRecord: ["Lewis Hamilton", "1:30.983", "2019"] as [string, string, string],
    notableMoments: ["Senna vs. Prost 1989 collision at the chicane", "2014 tragedy - Bianchi's crash in monsoon conditions"],
    overtakingRating: 3,
    bestSector: "The Esses (Turns 3–7)",
    direction: "Both (figure-8)",
    type: "Permanent",
    designer: "John Hugenholtz",
    mostWins: "Michael Schumacher (6)",
  },
  miami: {
    circuitId: "miami",
    country: "USA",
    city: "Miami Gardens",
    lengthKm: "5.412",
    laps: "57",
    turns: "19",
    topSpeedKmh: "350",
    elevationChangeM: "3",
    drsZones: 3,
    firstGp: 2022,
    description: "A temporary street-style layout built around Hard Rock Stadium in Miami Gardens, home of the NFL's Miami Dolphins. The circuit joined the calendar in 2022 as part of F1's American expansion push, and is characterised by two long straights bookending a fiddly, low-grip infield of tight 90-degree corners painted onto standard parking-lot asphalt. Grip evolves dramatically session-to-session as rubber lays down and washes off with each rain shower - teams often abandon setup work from FP1 because the surface is so different by qualifying. The main straight into Turn 1 tops out over 350 km/h with DRS, making it a genuine overtaking zone, while the Turn 11–13 chicane sequence is technical enough to reward late-braking specialists. Off-track theatrics - beach clubs, celebrity guests, and a fake marina made of blue tarpaulins - give Miami its distinctive Vegas-cousin identity. Verstappen's runaway 2023 win from P9 on the grid and Norris's maiden victory in 2024 (helped by well-timed safety car luck) have already given the venue two defining moments in its short history.",
    character: ["LOW-GRIP", "LONG-STRAIGHTS", "HYBRID-STREET"],
    lapRecord: ["Max Verstappen", "1:29.708", "2023"] as [string, string, string],
    notableMoments: ["Verstappen's runaway 2023 win from P9 on the grid", "Norris's maiden win in 2024 under safety car luck"],
    overtakingRating: 4,
    bestSector: "Turn 17 chicane",
    direction: "Clockwise",
    type: "Street",
    designer: "Apex Circuit Design",
    mostWins: "Max Verstappen (2)",
  },
  imola: {
    circuitId: "imola",
    country: "Italy",
    city: "Imola",
    lengthKm: "4.909",
    laps: "63",
    turns: "19",
    topSpeedKmh: "320",
    elevationChangeM: "30",
    drsZones: 1,
    firstGp: 1980,
    description: "Old-school, narrow, and utterly unforgiving - the Autodromo Enzo e Dino Ferrari runs anticlockwise through Tamburello, Villeneuve, Tosa and the Acque Minerali complex, hugging the banks of the Santerno river outside the town of Imola. Built in 1953 and named for Enzo Ferrari and his son Dino, the circuit sits just 40 km from Maranello and effectively serves as Ferrari's home race alongside Monza. Overtaking here is genuinely difficult in modern F1 machinery - the layout was designed for narrower cars from a different era, and qualifying position tends to define the race outcome more than at any track outside Monaco. The 1994 San Marino GP weekend remains the darkest in the sport's history: Roland Ratzenberger's Friday qualifying crash was followed by Ayrton Senna's Sunday accident at Tamburello, ending Senna's life and reshaping F1 safety standards forever. The chicanes that now bear their names were installed in the aftermath. Returning to the calendar in 2020 during the COVID-shortened season, Imola has since delivered memorable modern races - Verstappen's 0.7-second final-lap defence over Hamilton in 2022 among them - and its status as a heritage venue makes any threat of losing its slot deeply controversial with tifosi and drivers alike.",
    character: ["OLD-SCHOOL", "NARROW", "LOW-OVERTAKING"],
    lapRecord: ["Lewis Hamilton", "1:15.484", "2020"] as [string, string, string],
    notableMoments: ["Senna's death in 1994 - the darkest weekend in F1", "Verstappen edges Hamilton by 0.7s across the final lap in 2022"],
    overtakingRating: 2,
    bestSector: "Acque Minerali → Variante Alta",
    direction: "Anticlockwise",
    type: "Permanent",
    designer: "Alfredo Codega",
    mostWins: "Michael Schumacher (7)",
  },
  monaco: {
    circuitId: "monaco",
    country: "Monaco",
    city: "Monte Carlo",
    lengthKm: "3.337",
    laps: "78",
    turns: "19",
    topSpeedKmh: "300",
    elevationChangeM: "42",
    drsZones: 1,
    firstGp: 1950,
    description: "The crown jewel of the F1 calendar and the oldest race in world championship history - Monte Carlo has hosted a Grand Prix since 1929 and has been on the world championship since its inaugural year of 1950. Narrower than a football pitch, walls sitting inches from the racing line, elevation swings that climb from the harbour up through Massenet to Casino Square and drop back down through Mirabeau to the tunnel entrance - nothing else in F1 requires this combination of precision and courage. Overtaking is essentially impossible in modern cars, which has attracted growing criticism, but Monaco's value as a spectacle is unmatched: the yachts, the palace, the Casino, the Fairmont hairpin (the slowest corner in F1 at just 50 km/h). Every centimetre matters here - braking markers are measured in painted stripes on the wall, and a single locked wheel can end a race. The tunnel section transitions from bright Mediterranean sun into artificial light and back out again within four seconds, disorienting drivers and creating the visually striking corner-exit into the chicane. Senna's six wins remain the record; his 1988 qualifying lap - 1.4 seconds faster than teammate Prost - is regarded as perhaps the greatest single lap in F1 history.",
    character: ["STREET-CIRCUIT", "NO-OVERTAKING", "PRECISION"],
    lapRecord: ["Lewis Hamilton", "1:12.909", "2021"] as [string, string, string],
    notableMoments: ["Senna's 1988 pole - 1.4s faster than teammate Prost", "Panis wins from P14 in the 1996 rain lottery"],
    overtakingRating: 1,
    bestSector: "Swimming Pool complex",
    direction: "Clockwise",
    type: "Street",
    designer: "Antony Noghès (1929)",
    mostWins: "Ayrton Senna (6)",
  },
  catalunya: {
    circuitId: "catalunya",
    country: "Spain",
    city: "Barcelona",
    lengthKm: "4.657",
    laps: "66",
    turns: "14",
    topSpeedKmh: "325",
    elevationChangeM: "30",
    drsZones: 2,
    firstGp: 1991,
    description: "The Circuit de Barcelona-Catalunya has been F1's ultimate benchmark since it joined the calendar in 1991 - every team runs pre-season testing here, giving them thousands of laps of reference data across every conceivable setup and weather condition. If your car works at Catalunya, it works everywhere, which is why the \"Barcelona test\" phrase has become shorthand for real-world car validation. The layout is a study in progression: Turn 1 is a heavy braking zone from over 320 km/h, Turn 3 is a long-loaded right-hander that hammers the front-left tyre, and the flowing Turn 9 downhill entry demands commitment while the car is still finding grip. The old Turn 10 chicane returned in 2023 after a decade of complaints from drivers about the safety-mandated tighter version - restoring the natural flow of the final sector and dropping lap times by nearly a second. High-energy corners across every sector eat front tyres, making it a two-stop race even in cool conditions, and following another car through Sector 3 has traditionally been almost impossible due to dirty air - though the 2022 regulations improved things noticeably. Verstappen's F1 debut win here at 18 years old in 2016 (his very first race for Red Bull) remains one of the modern sport's most remarkable stories.",
    character: ["REFERENCE-TRACK", "BALANCED", "TYRE-DEG"],
    lapRecord: ["Max Verstappen", "1:16.330", "2023"] as [string, string, string],
    notableMoments: ["Verstappen's debut win in 2016 at 18 years old", "Schumacher vs. Alonso rain masterclass in 1996"],
    overtakingRating: 3,
    bestSector: "Turn 3 long right",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Ricardo Bofill",
    mostWins: "Michael Schumacher (6)",
  },
  villeneuve: {
    circuitId: "villeneuve",
    country: "Canada",
    city: "Montreal",
    lengthKm: "4.361",
    laps: "70",
    turns: "14",
    topSpeedKmh: "335",
    elevationChangeM: "6",
    drsZones: 3,
    firstGp: 1978,
    description: "The Circuit Gilles Villeneuve is a semi-permanent street layout built on Île Notre-Dame, a man-made island in the middle of the Saint Lawrence River created for Expo 67. Named for the late Canadian F1 legend after his death in 1982, the circuit is defined by its unusual character: long full-throttle straights linked by tight chicanes and hairpins that punish anyone late on the brakes. The legendary \"Wall of Champions\" at the exit of the final chicane has caught out Damon Hill, Michael Schumacher, and Jacques Villeneuve himself all in a single 1999 weekend - the wall lies exactly on the racing line for anyone who cuts the chicane too aggressively. Because the circuit is only used once a year, grip evolves dramatically session-to-session, and the abrasive asphalt combined with heavy braking events makes tyre wear one of the highest of the season. Weather is famously chaotic - rapid swings from bright sunshine to torrential downpours regularly turn the race into a safety-car-heavy lottery, with 2011 seeing a two-hour red flag and Jenson Button winning from P21 after six pit stops. The Turn 10 hairpin - labelled \"Épingle\" on maps - is one of the last true hairpins in F1, a slow, opening-radius corner that provides prime overtaking down the flat-out final straight.",
    character: ["STOP-AND-GO", "WALL-LINED", "LOW-DOWNFORCE"],
    lapRecord: ["Valtteri Bottas", "1:13.078", "2019"] as [string, string, string],
    notableMoments: ["Jenson Button wins from P21 after multiple pit stops in 2011", "Hamilton's maiden win in 2007 as a rookie"],
    overtakingRating: 4,
    bestSector: "Turn 10 hairpin",
    direction: "Clockwise",
    type: "Semi-permanent",
    designer: "Roger Peart",
    mostWins: "Michael Schumacher (7)",
  },
  red_bull_ring: {
    circuitId: "red_bull_ring",
    country: "Austria",
    city: "Spielberg",
    lengthKm: "4.318",
    laps: "71",
    turns: "10",
    topSpeedKmh: "325",
    elevationChangeM: "65",
    drsZones: 3,
    firstGp: 1970,
    description: "The Red Bull Ring (formerly the Österreichring, then A1-Ring) is a rollercoaster of a circuit set in the rolling Styrian mountains of Austria, purchased by Dietrich Mateschitz's Red Bull empire in 2004 and rebuilt to F1 standards for its 2014 return. Only 10 corners in total, but every single one matters - a lap takes barely 65 seconds, meaning traffic in qualifying and track limits at Turns 9 and 10 constantly define the story. The dramatic elevation change (65 metres from lowest to highest point) means Turn 3 is one of the sport's most photographed corners - cars climb up a steep hill under heavy braking from over 300 km/h to just 130 km/h in a matter of metres. The exit of Turn 4 is another classic overtaking spot into the tight left-hander at Turn 5, and Turns 6 and 7 flow together into a rhythm section that requires perfect car balance to unlock. Track limits are enforced ferociously here - Turns 9 and 10 have caught out drivers race after race, with a lap time deletion arriving within seconds of any wheel touching the outside white line. As Red Bull's home race, the venue has become a stronghold for Verstappen - his lap-64 sprint collision with Hamilton in 2021 remains one of the season's most controversial moments, and his lap-58 collision with Norris while battling for the lead in 2024 was arguably the year's most costly incident.",
    character: ["SHORT-LAP", "ELEVATION", "TRACK-LIMITS"],
    lapRecord: ["Carlos Sainz", "1:05.619", "2020"] as [string, string, string],
    notableMoments: ["Verstappen–Hamilton lap-64 collision in 2021 sprint", "Norris and Verstappen collide from the lead in 2024"],
    overtakingRating: 4,
    bestSector: "Turn 3 uphill braking",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Hermann Tilke",
    mostWins: "Max Verstappen (5)",
  },
  silverstone: {
    circuitId: "silverstone",
    country: "United Kingdom",
    city: "Silverstone",
    lengthKm: "5.891",
    laps: "52",
    turns: "18",
    topSpeedKmh: "330",
    elevationChangeM: "15",
    drsZones: 2,
    firstGp: 1950,
    description: "Silverstone hosted the very first Formula One World Championship race on 13 May 1950 - every subsequent decade of the sport traces back to this repurposed WWII bomber airfield in Northamptonshire. Built on the runways of RAF Silverstone, its high-speed character is a direct legacy of that flat, wide-open terrain - modern cars generate cornering forces here that regularly exceed 5g. The Copse–Maggotts–Becketts–Chapel sequence in Sector 1 is arguably the greatest high-speed corner complex in motorsport: cars flow from over 300 km/h through six direction changes in eight seconds, never dropping below 250 km/h, with the driver's neck, arms, and stomach absorbing sustained lateral G that few other places demand. Stowe corner remains a classic overtaking spot into the flat-out Vale-and-Club section that returns cars to the pit straight. The British GP crowd atmosphere - 480,000 across the weekend in 2023 - is unmatched anywhere except Monza, with Hamilton's eight home wins here (nine total counting 2024) generating the loudest cheers modern F1 has heard. The 2021 Copse collision between Hamilton and Verstappen - a 51g impact that put Verstappen in hospital and drew a controversial 10-second penalty for Hamilton - set the emotional tone for that year's title fight and remains one of the most debated moments in recent F1 history.",
    character: ["HIGH-SPEED", "HERITAGE", "HIGH-G"],
    lapRecord: ["Max Verstappen", "1:27.097", "2020"] as [string, string, string],
    notableMoments: ["Hamilton–Verstappen Copse crash on lap 1, 2021", "Hamilton's three-wheeled hobble to victory in 2020"],
    overtakingRating: 4,
    bestSector: "Maggotts–Becketts–Chapel (S1)",
    direction: "Clockwise",
    type: "Permanent",
    designer: "RAF Silverstone (1948)",
    mostWins: "Lewis Hamilton (9)",
  },
  spa: {
    circuitId: "spa",
    country: "Belgium",
    city: "Stavelot",
    lengthKm: "7.004",
    laps: "44",
    turns: "19",
    topSpeedKmh: "340",
    elevationChangeM: "102",
    drsZones: 2,
    firstGp: 1950,
    description: "The longest circuit on the F1 calendar at just over 7 kilometres, Spa-Francorchamps cuts through the dense Ardennes forest with 102 metres of elevation change from lowest to highest point. Originally 14 km long and using public roads through the villages of Malmedy and Stavelot, the circuit was cut down to its current shape in 1979 after two decades of fatal accidents on the original layout. Eau Rouge–Raidillon is the most famous corner in F1 - a compression at the bottom of a hill followed by a flat-out uphill left-right that loads the car under 4g before releasing it onto the Kemmel Straight at over 300 km/h. Modern ground-effect cars take the sequence flat, but the visual drama and physical brutality remain intact. Weather across the 7-kilometre loop is famously unpredictable - one end of the circuit can be in blazing sunshine while the other is under heavy rain, and the 1998 season saw a first-lap pileup at La Source that took out 13 cars in the opening seconds. Schumacher's F1 debut for Jordan in 1991 happened here, as did his first career win a year later for Benetton - his six victories at Spa remain the record. Other classic corners include Pouhon (a fast double-apex left downhill), Blanchimont (a flat-out kink at 300 km/h through the trees), and the Bus Stop chicane at the end of the lap.",
    character: ["LONG-LAP", "ELEVATION", "WEATHER-CHAOS"],
    lapRecord: ["Valtteri Bottas", "1:46.286", "2018"] as [string, string, string],
    notableMoments: ["Schumacher's debut here in 1991 and his first win a year later", "1998 pileup at La Source - 13 cars out on lap 1"],
    overtakingRating: 5,
    bestSector: "Eau Rouge → Raidillon",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Jean Stassen (1921)",
    mostWins: "Michael Schumacher (6)",
  },
  hungaroring: {
    circuitId: "hungaroring",
    country: "Hungary",
    city: "Budapest",
    lengthKm: "4.381",
    laps: "70",
    turns: "14",
    topSpeedKmh: "305",
    elevationChangeM: "35",
    drsZones: 2,
    firstGp: 1986,
    description: "The Hungaroring earned its enduring nickname \"Monaco without the walls\" the moment it joined the calendar in 1986 as the first F1 race behind the Iron Curtain - twisty, technical, and famously hard to overtake, but without the barriers pressing in on either side. Located in a natural amphitheatre 20 km northeast of Budapest, the layout is essentially a series of medium-speed corners connected by short straights, with no true full-throttle sections and DRS zones that rarely produce clean overtakes. Track position is everything: qualifying pace matters more here than at any circuit outside Monaco. The hot, dry conditions of a Central European July (recently pushed later into July or August) punish tyre management and cooling packages simultaneously - drivers report cockpit temperatures above 55°C, and radiator ducting on modern F1 cars is often reconfigured specifically for this weekend. Turn 1 downhill braking is one of the few overtaking spots, along with the tight Turn 2 hairpin that immediately follows. The Hungaroring has a habit of producing surprise winners - Damon Hill nearly won for Arrows in 1997, Jenson Button's wet-to-dry masterclass from P14 delivered him victory in 2006, and Esteban Ocon's maiden 2021 win in the chaos of the opening-lap wet pileup remain classic examples.",
    character: ["TECHNICAL", "TIGHT", "HIGH-DOWNFORCE"],
    lapRecord: ["Lewis Hamilton", "1:16.627", "2020"] as [string, string, string],
    notableMoments: ["Ocon's maiden win from P8 in 2021 chaos", "Button's wet-to-dry masterclass in 2006 from P14"],
    overtakingRating: 2,
    bestSector: "Turn 1 downhill braking",
    direction: "Clockwise",
    type: "Permanent",
    designer: "István Papp",
    mostWins: "Lewis Hamilton (8)",
  },
  zandvoort: {
    circuitId: "zandvoort",
    country: "Netherlands",
    city: "Zandvoort",
    lengthKm: "4.259",
    laps: "72",
    turns: "14",
    topSpeedKmh: "315",
    elevationChangeM: "18",
    drsZones: 2,
    firstGp: 1952,
    description: "Circuit Zandvoort returned to the F1 calendar in 2021 after a 36-year absence, riding the wave of Max Verstappen's rise and Dutch national enthusiasm. Originally built in 1948 on the coastal sand dunes near Amsterdam using WWII-era communication road foundations, the circuit was extensively modernised for its comeback - most notably with the addition of two banked corners: the Hugenholtz right-hander at Turn 3 (banking at 18°) and the Arie Luyendyk final corner at Turn 14 (banking at 18°, named for the Dutch IndyCar veteran). The banking is functional, not cosmetic - it allows cars to follow much more closely through those specific corners than a flat layout would permit, opening up genuine slipstreaming opportunities down the pit straight into Turn 1. But the narrow twisty middle sector still makes overtaking scarce elsewhere on the lap, so the race often turns on tyre strategy and safety car timing. The famously loud \"Orange Army\" of Dutch fans - many wearing head-to-toe orange and setting off orange smoke flares - has made Zandvoort one of the most atmospheric weekends of the season. Verstappen has won every Dutch GP since the return except 2024, when McLaren's pace briefly interrupted the streak. The 4.259-km loop remains one of the shortest on the calendar, meaning traffic in qualifying and race pace is a perpetual challenge.",
    character: ["BANKED-CORNERS", "NARROW", "OLD-SCHOOL"],
    lapRecord: ["Lewis Hamilton", "1:11.097", "2021"] as [string, string, string],
    notableMoments: ["Verstappen wins his home GP first time back - 2021", "Rain-hit 2023 race and Verstappen's 9th win in a row"],
    overtakingRating: 2,
    bestSector: "Turn 3 banking",
    direction: "Clockwise",
    type: "Permanent",
    designer: "John Hugenholtz",
    mostWins: "Niki Lauda / Jim Clark (4)",
  },
  monza: {
    circuitId: "monza",
    country: "Italy",
    city: "Monza",
    lengthKm: "5.793",
    laps: "53",
    turns: "11",
    topSpeedKmh: "360",
    elevationChangeM: "10",
    drsZones: 2,
    firstGp: 1950,
    description: "The Autodromo Nazionale Monza is known simply as the Temple of Speed - F1's fastest permanent circuit, and one of only three tracks (with Silverstone and Spa) to have hosted a race in every world championship season since 1950. Built in 1922 inside the Royal Villa of Monza park just outside Milan, the layout has evolved through multiple configurations, including the terrifying banked oval whose crumbling concrete banking is still visible from the modern track. Cars are on full throttle for over 75% of the lap, so teams run their lowest-downforce aerodynamic package of the entire season - sacrificing cornering grip everywhere for raw straight-line speed that peaks above 360 km/h. Slipstreaming defines qualifying strategy: any driver on a solo lap is at a fundamental disadvantage, which is why Q3 sees teams orchestrate careful tow arrangements between teammates that occasionally break down into farce (see: the 2019 Q3 processional). Overtaking is genuine at Turn 1 (Rettifilo), Della Roggia, and the Ascari chicane - the last of which is one of the sport's truly technical corners, a fast triple-apex that requires perfect car balance to link together. The tifosi make it the loudest weekend on the calendar, and Ferrari's Italian home race carries an emotional weight matched only by Monaco and Silverstone in their respective national contexts. Sainz's pole for Ferrari in 2024 was greeted with a track invasion the moment the chequered flag fell.",
    character: ["LOW-DOWNFORCE", "ULTRA-HIGH-SPEED", "HERITAGE"],
    lapRecord: ["Rubens Barrichello", "1:21.046", "2004"] as [string, string, string],
    notableMoments: ["Gasly's stunning maiden win for AlphaTauri in 2020", "Sainz pole for Ferrari at home in 2024"],
    overtakingRating: 4,
    bestSector: "Curva Grande + Della Roggia",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Alfredo Rosselli (1922)",
    mostWins: "Michael Schumacher (5)",
  },
  baku: {
    circuitId: "baku",
    country: "Azerbaijan",
    city: "Baku",
    lengthKm: "6.003",
    laps: "51",
    turns: "20",
    topSpeedKmh: "360",
    elevationChangeM: "12",
    drsZones: 2,
    firstGp: 2016,
    description: "The Baku City Circuit is a street layout of two dramatically different halves - a fiddly, walled castle section that threads through the narrow lanes of Baku's medieval Old City (Icherisheher), and a 2.2-kilometre flat-out straight along the Caspian Sea seafront that regularly produces the highest top speeds of the entire calendar. Designed by Hermann Tilke to open F1 up to the Caucasus in 2016, the layout was called \"the Monaco with a straight\" by drivers before they realised how much crazier it actually is. The castle section rewards absolute precision - walls sit centimetres from the racing line at Turn 8 (the tightest and most claustrophobic section), where cars barely fit between the stone buildings on either side. The long back straight into the heavy braking of Turn 1 transforms qualifying into a slipstreaming chess game: any driver on a solo lap is disadvantaged, but sitting behind a tow means dirty air through the entire castle section. Chaos is the default outcome - the 2017 race saw Vettel deliberately drive into Hamilton behind the safety car, 2018 delivered the Verstappen–Ricciardo Red Bull collision that ended their team-mate relationship, and Hamilton's lock-up at Turn 1 in 2021 handed Sergio Pérez the victory after Verstappen's late tyre failure. Safety cars appear in almost every race.",
    character: ["LONG-STRAIGHT", "STREET-CIRCUIT", "CHAOS-PRONE"],
    lapRecord: ["Charles Leclerc", "1:43.009", "2019"] as [string, string, string],
    notableMoments: ["Verstappen–Ricciardo Red Bull collision in 2018", "Verstappen tyre failure and Hamilton lock-up handing Perez the 2021 win"],
    overtakingRating: 5,
    bestSector: "Turn 1 into the castle",
    direction: "Anticlockwise",
    type: "Street",
    designer: "Hermann Tilke",
    mostWins: "Sergio Pérez / Nico Rosberg (2)",
  },
  marina_bay: {
    circuitId: "marina_bay",
    country: "Singapore",
    city: "Marina Bay",
    lengthKm: "4.940",
    laps: "62",
    turns: "19",
    topSpeedKmh: "320",
    elevationChangeM: "5",
    drsZones: 3,
    firstGp: 2008,
    description: "The Marina Bay Street Circuit - F1's original night race and the toughest physical challenge of the year for both drivers and machinery. Introduced in 2008 as F1 first attempted to broadcast into European primetime while racing in Asia, the circuit is illuminated by 1,500 lighting projectors arranged around the harbour, producing daylight-quality visibility from twilight to the chequered flag. Humidity above 70% and cockpit temperatures beyond 60°C make it the ultimate endurance test - drivers routinely lose 3+ kilograms of body weight during the race, and it is one of the only rounds that regularly hits the two-hour time limit before completing the scheduled 62 laps. There are no true cooling straights on the layout, so cooling packages must be balanced against the drag penalty they impose. The 2023 revisions smoothed the previous tight Turn 16–19 chicane into a single flowing kink, dropping lap times by nearly 20 seconds and finally giving cars a chance to breathe between the fiddly middle-sector wall sections and the pit straight. The 2008 Singapore GP produced one of the sport's ugliest scandals - Renault ordered Nelson Piquet Jr to deliberately crash so that a safety car would benefit teammate Fernando Alonso, who duly won. Sainz's 2023 victory ended Red Bull's 15-race winning streak in dramatic fashion, keeping Verstappen honest at the peak of his dominance.",
    character: ["NIGHT-RACE", "PHYSICAL", "STREET-CIRCUIT"],
    lapRecord: ["Lando Norris", "1:34.486", "2024"] as [string, string, string],
    notableMoments: ["Crashgate - Piquet Jr's ordered crash gives Alonso the 2008 win", "Sainz breaks Red Bull's 15-race streak in 2023"],
    overtakingRating: 2,
    bestSector: "Turn 5–7 back straight",
    direction: "Anticlockwise",
    type: "Street",
    designer: "Hermann Tilke",
    mostWins: "Sebastian Vettel (5)",
  },
  americas: {
    circuitId: "americas",
    country: "USA",
    city: "Austin",
    lengthKm: "5.513",
    laps: "56",
    turns: "20",
    topSpeedKmh: "325",
    elevationChangeM: "40",
    drsZones: 2,
    firstGp: 2012,
    description: "The Circuit of the Americas - universally known as COTA - was purpose-built for F1's 2012 return to the United States, on a rural site 15 miles southeast of Austin. Designed by Hermann Tilke with explicit inspiration drawn from great corners around the world, the layout is essentially a \"greatest hits\" compilation: the uphill blind Turn 1 mirrors Silverstone's Copse in terms of commitment required, the Turn 3–6 esses replicate the rhythm and load of Suzuka's Sector 1, and the Turn 11 hairpin echoes Hockenheim's pre-2002 stadium section. The 40-metre elevation gain from the finish line to Turn 1 makes for one of the most dramatic opening sequences in F1 - spectators at the flagpole viewing area can see the entire pack disappear over the ridge in a single frame. Bumpy surface issues have haunted the circuit almost since it opened: Texas soil subsidence beneath the asphalt causes localised bumps that get progressively worse each year until FIA-mandated resurfacing addresses them. The 2023 race delivered a headline-grabbing moment when Lewis Hamilton and Charles Leclerc were both disqualified post-race for excessive plank wear - a direct consequence of running the car low over a bumpy track - with Verstappen inheriting a race victory he had already earned on the road. Verstappen has won every US GP since 2021 during his three-championship run.",
    character: ["MIXED-INSPIRATION", "ELEVATION", "BUMPY"],
    lapRecord: ["Charles Leclerc", "1:36.169", "2019"] as [string, string, string],
    notableMoments: ["Verstappen wins his first US GP in 2021 title fight", "Hamilton disqualification for plank wear in 2023"],
    overtakingRating: 4,
    bestSector: "Uphill Turn 1",
    direction: "Anticlockwise",
    type: "Permanent",
    designer: "Hermann Tilke",
    mostWins: "Lewis Hamilton (5)",
  },
  rodriguez: {
    circuitId: "rodriguez",
    country: "Mexico",
    city: "Mexico City",
    lengthKm: "4.304",
    laps: "71",
    turns: "17",
    topSpeedKmh: "360",
    elevationChangeM: "5",
    drsZones: 3,
    firstGp: 1963,
    description: "The Autódromo Hermanos Rodríguez sits 2,240 metres above sea level in Mexico City - the highest-altitude circuit on the F1 calendar and the thinnest air any modern F1 car has to breathe during a race weekend. Engines lose approximately 20% of their normal peak power due to the reduced oxygen density, and aerodynamic downforce drops by roughly a third at the same wing settings - so paradoxically, teams run their highest-downforce Monaco-style wing packages here and still record among the calendar's highest top speeds on the vast pit straight. The circuit is named for brothers Ricardo and Pedro Rodríguez, both Mexican F1 drivers of the 1960s (both killed while racing), and holds a special national significance - the sport's return in 2015 after a 23-year absence was greeted with attendance figures that consistently rank in the top three of the season. The stadium section from Turn 13 to Turn 17 threads through the former baseball stadium's permanent grandstands, giving crowd noise levels that rival Silverstone and Monza. Turn 1 is a heavy braking zone from over 350 km/h into a downhill left-hander that regularly produces safety car incidents. Sergio Pérez's podium at his home race, and Verstappen's championship-clinching 2021 victory (the first of his three consecutive titles), remain the venue's defining recent moments.",
    character: ["HIGH-ALTITUDE", "LONG-STRAIGHT", "STADIUM"],
    lapRecord: ["Valtteri Bottas", "1:17.774", "2021"] as [string, string, string],
    notableMoments: ["Perez podium in front of home crowd - dream fulfilled", "Verstappen becoming 2021 champion with a win here"],
    overtakingRating: 4,
    bestSector: "Stadium section (T13–T17)",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Óscar F. Fernández",
    mostWins: "Max Verstappen (4)",
  },
  interlagos: {
    circuitId: "interlagos",
    country: "Brazil",
    city: "São Paulo",
    lengthKm: "4.309",
    laps: "71",
    turns: "15",
    topSpeedKmh: "335",
    elevationChangeM: "43",
    drsZones: 2,
    firstGp: 1973,
    description: "The Autódromo José Carlos Pace - known everywhere as Interlagos - sits on high ground in São Paulo's southern suburbs at 800 metres above sea level, and remains one of only a handful of anticlockwise circuits on the F1 calendar. Named for the Brazilian F1 driver who died in a 1977 light aircraft crash, the layout was originally 8 kilometres long when it opened in 1940 and is now down to its modern 4.3-kilometre configuration used since 1990. The Senna S opening complex - Turn 1 (a downhill left) into Turn 2 (a rising right) - flows relentlessly downhill and is one of the sport's most photographed corner sequences. The Descida do Lago (Descent to the Lake) section that follows drops the circuit further before the long uphill drag back to the pit straight - the elevation change and forward camber on the run to Turn 1 create prime overtaking opportunities lap after lap. Weather is famously unpredictable and championship-defining races have happened here almost every year: Hamilton's 2008 final-corner title snatch from Massa remains the most emotional F1 title finale ever televised, Vettel and Webber's teammate collision decided the 2010 title, Verstappen won his 2024 wet-race masterclass from P17 to effectively wrap up that year's championship. The circuit's combination of low grip, high altitude thin air, and rapid weather changes has produced more chaos per lap than almost anywhere else on the calendar.",
    character: ["ANTICLOCKWISE", "WEATHER-CHAOS", "DRAMATIC"],
    lapRecord: ["Valtteri Bottas", "1:10.540", "2018"] as [string, string, string],
    notableMoments: ["Hamilton's 2008 final-corner championship snatch", "Verstappen's wet-race masterclass from P17 in 2024"],
    overtakingRating: 4,
    bestSector: "Senna S (Turns 1–2)",
    direction: "Anticlockwise",
    type: "Permanent",
    designer: "Óscar F. de Sousa",
    mostWins: "Michael Schumacher / Alain Prost (6)",
  },
  vegas: {
    circuitId: "vegas",
    country: "USA",
    city: "Las Vegas",
    lengthKm: "6.201",
    laps: "50",
    turns: "17",
    topSpeedKmh: "350",
    elevationChangeM: "3",
    drsZones: 2,
    firstGp: 2023,
    description: "The Las Vegas Strip Circuit is F1's highest-stakes commercial gamble in decades - a Saturday-night race staged in the heart of the Strip that runs past the Sphere, Caesars Palace, Bellagio, and the Venetian in the space of a single lap. Owned and promoted directly by Formula One Group rather than a third-party promoter, the circuit represents Liberty Media's biggest bet on the American market and cost over $500 million to establish including permanent pit facilities. Purpose-built for maximum overtaking, the layout consists mostly of 90-degree corners linking two extremely long straights, making it fundamentally a slipstreaming and heavy-braking exercise where late-braking specialists thrive. Cold desert nights (November temperatures often drop below 10°C during the race) combined with a street-circuit that is only used once a year create genuinely difficult tyre-warm-up conditions - the 2023 debut race saw multiple drivers spin on their outlaps as Pirellis simply refused to reach operating temperature. The rubber-in evolution across each session is dramatic. The debut year delivered an all-time classic - Verstappen and Leclerc traded the lead multiple times before Verstappen prevailed with a late move, and Sainz's brutal drainage-cover incident in FP1 caused a two-hour session cancellation and a fan refund controversy. Russell's 2024 win came from Norris and Verstappen colliding at the front.",
    character: ["NIGHT-RACE", "LONG-STRAIGHT", "COLD-TARMAC"],
    lapRecord: ["Oscar Piastri", "1:34.876", "2024"] as [string, string, string],
    notableMoments: ["Verstappen–Leclerc scrap over the 2023 win, three lead changes", "Russell wins in 2024 as Norris and Verstappen swap contact"],
    overtakingRating: 4,
    bestSector: "Strip straight into T14",
    direction: "Anticlockwise",
    type: "Street",
    designer: "Carsten Tilke",
    mostWins: "Max Verstappen / George Russell (1)",
  },
  losail: {
    circuitId: "losail",
    country: "Qatar",
    city: "Lusail",
    lengthKm: "5.419",
    laps: "57",
    turns: "16",
    topSpeedKmh: "325",
    elevationChangeM: "3",
    drsZones: 1,
    firstGp: 2021,
    description: "The Lusail International Circuit was originally built in 2004 as a purpose-designed MotoGP venue, hosting the two-wheel world championship for two decades before joining F1's calendar in 2021. Its high-speed, flowing character was tuned for motorcycle racing, and translating that to F1 revealed unusual tyre-stress problems - long, sustained-load corners in the middle sector generate lateral G-forces on tyre sidewalls that neither Pirelli nor the drivers had experienced elsewhere on the calendar. The 2023 race saw multiple tyre failures during practice sessions, forcing the FIA and Pirelli to impose mandatory 18-lap maximum stints for the race itself to protect sidewall integrity - an unprecedented mid-weekend rule change. Cars are on full throttle nearly 80% of the lap, so teams run their lowest-downforce Monza-style packages. The desert environment presents cooling challenges but not the same tyre degradation as Bahrain, since the surface is less abrasive. Sitting under floodlights just outside Doha, the race is one of only a handful of true night races on the calendar. Verstappen was crowned 2023 world champion during the Sprint on the Saturday of this weekend, becoming the first driver ever to seal a title in a sprint session, before going on to win the main race the following day.",
    character: ["HIGH-SPEED", "FLOWING", "TYRE-STRESS"],
    lapRecord: ["Lando Norris", "1:22.384", "2024"] as [string, string, string],
    notableMoments: ["Verstappen crowned 2023 champion during the Sprint", "Hamilton's podium in 2021 as Bottas fought from the back"],
    overtakingRating: 3,
    bestSector: "Turns 12–14 sweepers",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Alain Prost & Ricardo Bofill",
    mostWins: "Max Verstappen (2)",
  },
  yas_marina: {
    circuitId: "yas_marina",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    lengthKm: "5.281",
    laps: "58",
    turns: "16",
    topSpeedKmh: "325",
    elevationChangeM: "4",
    drsZones: 2,
    firstGp: 2009,
    description: "The Yas Marina Circuit is the F1 calendar's traditional season closer - a twilight-to-night race that starts under the setting sun and finishes with cars threading under the illuminated arch of the Yas Viceroy Hotel spanning the pit lane. Located on Yas Island, part of Abu Dhabi's tourism development strategy, the circuit opened in 2009 as a Hermann Tilke design intended to be the \"most spectacular\" venue in F1 - but instead earned an early reputation as a boring, overtaking-hostile track that killed championship suspense. The 2021 redesign addressed those criticisms comprehensively: the North Hairpin was flowed into a banked left-hander, the middle-sector chicane sequence was replaced with a faster sweeping section, and DRS zone lengths were extended. The changes dramatically increased overtaking numbers and revitalised the season finale format. Marbles (small pieces of degraded rubber that build up off the racing line) make the Sunday race particularly tricky - any driver forced offline in a battle risks compromising an entire stint. The 2021 finale delivered the most controversial title ending in modern F1 history: Verstappen won his first championship on the final lap after race director Michael Masi's interpretation of the safety car procedure allowed a one-lap restart following Nicholas Latifi's crash. Piastri's pole in 2024 set up Norris's title-defining weekend as McLaren locked up the constructors'.",
    character: ["SEASON-CLOSER", "TWILIGHT", "BANKED"],
    lapRecord: ["Max Verstappen", "1:26.103", "2021"] as [string, string, string],
    notableMoments: ["Verstappen wins the 2021 title on the final lap - Latifi crash aftermath", "Piastri's first pole in 2024 setting up Norris's title"],
    overtakingRating: 4,
    bestSector: "Turn 6 banked left",
    direction: "Anticlockwise",
    type: "Permanent",
    designer: "Hermann Tilke",
    mostWins: "Lewis Hamilton (5)",
  },
  madring: {
    circuitId: "madring",
    country: "Spain",
    city: "Madrid",
    lengthKm: "5.474",
    laps: "57",
    turns: "20",
    topSpeedKmh: "345",
    elevationChangeM: "30",
    drsZones: 3,
    firstGp: 2026,
    description: "The Madring - officially the Madrid Grand Prix venue - represents F1's biggest new-venue commitment since the Miami debut in 2022. Set to join the calendar in September 2026, the circuit is being built as a hybrid layout around the IFEMA convention centre north of Madrid: partially permanent racing surface, partially street sections through the surrounding infrastructure. Design work has been led by Fenwick Iribarren Architects (best known for their World Cup stadium designs) with input from F1's own circuit engineering group, and the layout has been explicitly designed with overtaking as a first-order requirement - a lesson learned from the criticism levelled at earlier Tilke-era permanent circuits. The signature feature is the Peineta banking, a steeply banked corner (angles reportedly steeper than Zandvoort's 18°) that will allow cars to run side-by-side through what would otherwise be a single-file corner. A lengthy back straight punctuates the middle of the lap for slipstreaming and DRS overtaking. The venue will host Spain's only Grand Prix from 2026 onwards, taking the \"Spanish GP\" designation from Barcelona's Catalunya circuit which loses its calendar slot as part of the same contract change. Complete construction was ongoing into 2026 as the debut race approaches.",
    character: ["NEW-BUILD", "HYBRID-LAYOUT", "BANKED"],
    lapRecord: ["-", "-", "-"] as [string, string, string],
    notableMoments: ["Debut race in September 2026", "Peineta banking billed as steeper than Zandvoort's"],
    overtakingRating: 4,
    bestSector: "Peineta banking",
    direction: "Clockwise",
    type: "Hybrid",
    designer: "Fenwick Iribarren Architects",
    mostWins: "-",
  },
  sepang: {
    circuitId: "sepang",
    country: "Malaysia",
    city: "Kuala Lumpur",
    lengthKm: "5.543",
    laps: "56",
    turns: "15",
    topSpeedKmh: "325",
    elevationChangeM: "15",
    drsZones: 2,
    firstGp: 1999,
    description: "Sepang International Circuit was Hermann Tilke's first F1 commission, and it set the template for every \"Tilke-drome\" that followed: wide, cambered corners with generous run-off, a long back straight built for overtaking, and a modern pit/paddock complex unlike anything on the calendar at the time. It hosted the Malaysian Grand Prix from 1999 until 2017, when rising costs and falling attendance ended the race's run - the layout is now returning to the F1 calendar for the first time since, hosting a relocated round. The circuit is infamous among drivers and crews for its climate: equatorial heat and humidity push cockpit temperatures to some of the highest seen all year, and the surrounding jungle can turn a dry session into a torrential downpour with almost no warning. The wide, sweeping Turns 1–2 complex right after the pit straight is the signature feature, built deliberately wide enough for two and three-abreast racing into the first corner.",
    character: ["HIGH-HUMIDITY", "WIDE-RADIUS", "FLOWING"],
    lapRecord: ["Kimi Räikkönen", "1:34.223", "2016"] as [string, string, string],
    notableMoments: ["1999: Ferrari 1-2 disqualified post-race over a barge-board technicality, then reinstated on appeal", "2015: Vettel wins on just his second start for Ferrari, breaking Mercedes' perfect start to the season"],
    overtakingRating: 4,
    bestSector: "Turns 1–2 (wide, cambered double-apex)",
    direction: "Clockwise",
    type: "Permanent",
    designer: "Hermann Tilke",
    mostWins: "Lewis Hamilton (3)",
  },
};

export const ALL_CIRCUIT_FACTS: CircuitFacts[] = Object.values(CIRCUIT_FACTS);

/**
 * Ported from CircuitFacts.forCircuit — exact circuit_id first (both ways,
 * substring: ids can drift between seasons and datasets), then locality
 * (exact, then substring — "Monte Carlo" contains "Carlo"), then country.
 * Locality/country are last-resort fallbacks for when the id itself
 * doesn't match anything curated.
 */
export function forCircuit(circuitId: string, locality?: string, country?: string): CircuitFacts | null {
  const id = circuitId.toLowerCase().trim();
  if (CIRCUIT_FACTS[id]) return CIRCUIT_FACTS[id];
  for (const f of ALL_CIRCUIT_FACTS) {
    if (f.circuitId.includes(id) || id.includes(f.circuitId)) return f;
  }

  if (locality) {
    const loc = locality.toLowerCase().trim();
    for (const f of ALL_CIRCUIT_FACTS) {
      if (f.city.toLowerCase() === loc) return f;
    }
    for (const f of ALL_CIRCUIT_FACTS) {
      const city = f.city.toLowerCase();
      if (city.includes(loc) || loc.includes(city)) return f;
    }
  }

  if (country) {
    const c = country.toLowerCase().trim();
    for (const f of ALL_CIRCUIT_FACTS) {
      if (f.country.toLowerCase() === c) return f;
    }
  }

  return null;
}
